import type { NormaGuide } from "@/types";

export const normas: NormaGuide[] = [
  {
    nr: "NR-1",
    title: "Disposições Gerais e Gerenciamento de Riscos Ocupacionais",
    summary: "Norma base que estabelece os princípios aplicáveis a todas as demais NRs e institui o Programa de Gerenciamento de Riscos (PGR).",
    appliesTo: "Todas as empresas com empregados regidos pela CLT",
    obligations: [
      "Elaborar e implementar o PGR (Programa de Gerenciamento de Riscos)",
      "Identificar e avaliar todos os perigos e riscos ocupacionais",
      "Implementar medidas de controle hierarquizadas",
      "Incluir riscos psicossociais no escopo do PGR",
      "Manter documentação do PGR atualizada e acessível",
    ],
    penalties: "Multa de R$ 670 a R$ 33.000 conforme gravidade. Agravante em caso de acidente.",
    lastUpdate: "2024",
    category: "SST",
  },
  {
    nr: "NR-4",
    title: "Serviços Especializados em Engenharia de Segurança e em Medicina do Trabalho (SESMT)",
    summary: "Define obrigações de manter profissionais especializados em SST (médico do trabalho, engenheiro de segurança, técnico de segurança) conforme o grau de risco e número de empregados.",
    appliesTo: "Empresas com empregados conforme Quadro I da NR-4 (varia por setor e número de funcionários)",
    obligations: [
      "Dimensionar o SESMT conforme Quadro II da NR-4",
      "Manter profissionais habilitados nas especialidades exigidas",
      "Emitir PPRA/PGR, PCMSO e demais programas obrigatórios",
      "Participar das reuniões da CIPA",
      "Registrar o SESMT no Ministério do Trabalho",
    ],
    penalties: "Multa proporcional ao número de irregularidades encontradas. Pode resultar em embargo ou interdição.",
    lastUpdate: "2022",
    category: "SST",
  },
  {
    nr: "NR-5",
    title: "Comissão Interna de Prevenção de Acidentes (CIPA)",
    summary: "Regulamenta a Comissão Interna de Prevenção de Acidentes, composta por representantes dos empregados e empregadores, com mandato de 1 ano.",
    appliesTo: "Empresas conforme Quadro I da NR-5, em geral a partir de 20-50 funcionários dependendo do setor",
    obligations: [
      "Realizar eleição da CIPA anualmente com processo formal",
      "Garantir mandato de 1 ano com direito a uma reeleição",
      "Realizar reuniões mensais documentadas em ata",
      "Desenvolver o Mapa de Riscos",
      "Promover a Semana Interna de Prevenção de Acidentes (SIPAT)",
    ],
    penalties: "Multa de R$ 402 a R$ 4.020 por irregularidade. Membros da CIPA têm estabilidade; dispensa indevida gera passivo trabalhista.",
    lastUpdate: "2023",
    category: "SST",
  },
  {
    nr: "NR-6",
    title: "Equipamentos de Proteção Individual (EPI)",
    summary: "Regulamenta o fornecimento gratuito, a utilização, guarda e conservação dos EPIs pelo empregador, bem como as obrigações dos trabalhadores.",
    appliesTo: "Todas as empresas com empregados CLT onde haja riscos que justifiquem o uso de EPI",
    obligations: [
      "Fornecer EPI gratuitamente e em perfeito estado",
      "Exigir uso adequado dos EPIs pelo trabalhador",
      "Adquirir apenas EPIs com Certificado de Aprovação (CA) do MTE",
      "Treinar trabalhadores para uso correto dos EPIs",
      "Manter ficha de controle de entrega de EPI com assinatura do trabalhador",
    ],
    penalties: "Multa de R$ 402 a R$ 4.020 por irregularidade. Agravante em caso de acidente por ausência de EPI.",
    lastUpdate: "2018",
    category: "SST",
  },
  {
    nr: "NR-7",
    title: "Programa de Controle Médico de Saúde Ocupacional (PCMSO)",
    summary: "Estabelece a obrigatoriedade do PCMSO, que define os exames médicos obrigatórios (admissional, periódico, de retorno, mudança de função e demissional).",
    appliesTo: "Todas as empresas com empregados CLT",
    obligations: [
      "Elaborar e implementar o PCMSO anualmente",
      "Realizar exames médicos admissional, periódico, de retorno, de mudança de função e demissional",
      "Emitir Atestado de Saúde Ocupacional (ASO) após cada exame",
      "Enviar dados dos ASOs ao eSocial (evento S-2220)",
      "Manter prontuários médicos dos trabalhadores por 20 anos",
    ],
    penalties: "Multa de R$ 670 a R$ 33.000 por irregularidade.",
    lastUpdate: "2021",
    category: "SST",
  },
  {
    nr: "NR-9",
    title: "Avaliação e Controle das Exposições Ocupacionais a Agentes Físicos, Químicos e Biológicos",
    summary: "Define metodologias para identificação, avaliação quantitativa e controle de agentes nocivos no ambiente de trabalho.",
    appliesTo: "Empresas com empregados expostos a agentes físicos (ruído, calor, radiações), químicos ou biológicos",
    obligations: [
      "Realizar avaliação quantitativa dos agentes conforme metodologias da NR-9",
      "Adotar medidas de controle quando os limites de tolerância forem superados",
      "Hierarquizar medidas: eliminação > substituição > controles de engenharia > EPIs",
      "Documentar as avaliações no PGR e no Laudo Técnico de Condições Ambientais (LTCAT)",
      "Enviar dados ao eSocial (evento S-2240)",
    ],
    penalties: "Multa de R$ 2.012 a R$ 201.230 para casos graves. Adicional de insalubridade pode ser exigido judicialmente.",
    lastUpdate: "2021",
    category: "SST",
  },
  {
    nr: "NR-10",
    title: "Segurança em Instalações e Serviços em Eletricidade",
    summary: "Estabelece os requisitos para trabalhos em instalações elétricas e proximidades, exigindo capacitação específica dos trabalhadores.",
    appliesTo: "Empresas cujos trabalhadores atuam direta ou indiretamente em instalações elétricas",
    obligations: [
      "Capacitar trabalhadores conforme NR-10 básico ou habilitação elétrica (SEP)",
      "Elaborar Procedimentos de Trabalho para atividades elétricas",
      "Implementar medidas de controle específicas (distâncias de segurança, bloqueio/etiquetagem)",
      "Fornecer EPIs e ferramentas adequadas para trabalho elétrico",
      "Manter documentação atualizada das instalações elétricas",
    ],
    penalties: "Multa de R$ 1.200 a R$ 120.000 por infração. Trabalho em instalações elétricas sem habilitação pode configurar crime.",
    lastUpdate: "2022",
    category: "SST",
  },
  {
    nr: "NR-15",
    title: "Atividades e Operações Insalubres",
    summary: "Define as atividades que geram o adicional de insalubridade (10%, 20% ou 40% do salário mínimo) e os limites de tolerância para agentes nocivos.",
    appliesTo: "Empresas com trabalhadores expostos a agentes químicos, físicos ou biológicos acima dos limites de tolerância estabelecidos nos Anexos da NR-15",
    obligations: [
      "Avaliar exposição dos trabalhadores aos agentes dos Anexos da NR-15",
      "Pagar adicional de insalubridade correspondente ao grau (mínimo, médio, máximo)",
      "Buscar eliminar ou reduzir a insalubridade como prioridade",
      "Documentar os Laudos de Insalubridade (assinado por Engenheiro de Segurança ou Médico do Trabalho)",
      "Revisar os laudos quando houver mudanças no processo",
    ],
    penalties: "Ação trabalhista para pagamento retroativo do adicional + juros e correção. Multa administrativa de R$ 402 a R$ 4.020.",
    lastUpdate: "2022",
    category: "SST",
  },
  {
    nr: "NR-17",
    title: "Ergonomia",
    summary: "Estabelece parâmetros para adaptar as condições de trabalho às características psicofisiológicas dos trabalhadores, abrangendo levantamento de cargas, mobiliário, equipamentos e organização do trabalho.",
    appliesTo: "Todas as empresas com empregados, com foco especial em setores com alto risco ergonômico (telemarketing, caixas de banco, indústria manufatureira)",
    obligations: [
      "Elaborar a Análise Ergonômica do Trabalho (AET) para postos de risco",
      "Adequar mobiliário, equipamentos e organização do trabalho",
      "Respeitar limites de levantamento de cargas (23kg homens / 15kg mulheres em condições habituais)",
      "Garantir pausas obrigatórias para atividades com alto grau repetitividade",
      "Incluir riscos ergonômicos no PGR",
    ],
    penalties: "Multa de R$ 402 a R$ 4.020. Responsabilidade civil por LER/DORT (lesões por esforço repetitivo) pode resultar em ações milionárias.",
    lastUpdate: "2021",
    category: "SST",
  },
  {
    nr: "NR-35",
    title: "Trabalho em Altura",
    summary: "Define requisitos mínimos para trabalhos em altura (acima de 2 metros do nível inferior), incluindo planejamento, organização, capacitação e medidas de proteção.",
    appliesTo: "Todas as empresas cujos trabalhadores executam atividades a partir de 2 metros acima do nível inferior",
    obligations: [
      "Capacitar os trabalhadores para trabalho em altura (carga horária mínima definida na NR-35)",
      "Elaborar Análise de Risco (AR) antes de cada trabalho em altura",
      "Emitir Permissão de Trabalho (PT) para trabalhos de risco crítico",
      "Fornecer EPIs específicos: cinto de segurança tipo paraquedista, trava-queda, capacete",
      "Inspecionar todos os EPIs antes do início das atividades",
    ],
    penalties: "Multa de R$ 1.200 a R$ 120.000. Queda em altura é uma das principais causas de acidentes fatais no trabalho.",
    lastUpdate: "2012",
    category: "SST",
  },
];

export function getAllNormas(): NormaGuide[] {
  return normas;
}

export function getNormaByNr(nr: string): NormaGuide | undefined {
  return normas.find((n) => n.nr === nr);
}
